package com.blackrussia.game.vostok.account;

public enum AccountState {
    NOT_INITIALIZED,
    BACKEND_NOT_CONFIGURED,
    SIGNED_OUT,
    REQUESTING_EMAIL_CODE,
    WAITING_EMAIL_CODE,
    AUTHORIZING_PROVIDER,
    RESTORING_SESSION,
    LOADING_ACCOUNT,
    CHARACTER_CREATION_REQUIRED,
    CHARACTER_SELECTION_REQUIRED,
    READY_TO_PLAY,
    REQUESTING_GAME_TICKET,
    ERROR
}
